import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { buildAll } from '../scripts/build-userscripts.mjs';

const RAW_BASE = 'https://raw.githubusercontent.com/dzshzx/custom-user-js-scripts/master';

function entryMetadata(scriptId, extraLines = []) {
  return [
    '// ==UserScript==',
    `// @name         Demo ${scriptId}`,
    '// @namespace    https://example.invalid/demo',
    '// @version      1.2.3',
    '// @description  Demo build fixture.',
    '// @match        https://example.com/*',
    ...extraLines,
    `// @downloadURL  ${RAW_BASE}/dist/${scriptId}.user.js`,
    `// @updateURL    ${RAW_BASE}/dist/${scriptId}.user.js`,
    '// ==/UserScript==',
  ].join('\n');
}

async function createWorkspace() {
  const rootDir = await mkdtemp(path.join(os.tmpdir(), 'build-userscripts-'));
  const scriptDir = path.join(rootDir, 'src', 'userscripts', 'demo-script');
  await mkdir(scriptDir, { recursive: true });

  await writeFile(path.join(scriptDir, 'demo-script-greeting.lib.js'), [
    "export function greetingText(name) {",
    "  return `你好, ${name}`;",
    '}',
    '',
  ].join('\n'));
  await writeFile(path.join(scriptDir, 'demo-script-banner.lib.js'), [
    "import { greetingText } from './demo-script-greeting.lib.js';",
    '',
    'export function bannerText() {',
    "  return greetingText('近7天');",
    '}',
    '',
  ].join('\n'));
  await writeFile(path.join(scriptDir, 'demo-script.entry.js'), [
    entryMetadata('demo-script'),
    '',
    "import { bannerText } from './demo-script-banner.lib.js';",
    '',
    '(function () {',
    "  'use strict';",
    '  console.log(bannerText());',
    '})();',
    '',
  ].join('\n'));

  return { rootDir, scriptDir, distDir: path.join(rootDir, 'dist') };
}

test('buildAll bundles an entry into a metadata-headed single-file userscript', async (t) => {
  const { rootDir, distDir } = await createWorkspace();
  t.after(() => rm(rootDir, { recursive: true, force: true }));

  const results = await buildAll({ rootDir, distDir });
  assert.deepEqual(results.map((r) => r.scriptId), ['demo-script']);

  const bundled = await readFile(path.join(distDir, 'demo-script.user.js'), 'utf8');
  assert.ok(bundled.startsWith('// ==UserScript=='));
  assert.match(bundled, /@version\s+1\.2\.3/);
  assert.match(bundled, /GENERATED by scripts\/build-userscripts\.mjs/);
  for (const line of bundled.split('\n')) {
    assert.doesNotMatch(line, /^(import|export)\s/);
  }
  assert.ok(bundled.includes('greetingText'));
  assert.ok(bundled.includes('bannerText'));
  assert.ok(bundled.includes('你好'), 'charset utf8 keeps CJK literal');
  assert.equal(bundled.includes('@require'), false);
});

test('buildAll writes a legacy-path bridge that is byte-identical to the dist bundle', async (t) => {
  // The bridge must be the full script: script managers may install whatever the
  // legacy @downloadURL serves, and a stub would strand them on a no-op shell.
  const { rootDir, scriptDir, distDir } = await createWorkspace();
  t.after(() => rm(rootDir, { recursive: true, force: true }));

  await buildAll({ rootDir, distDir });

  const bundled = await readFile(path.join(distDir, 'demo-script.user.js'), 'utf8');
  const bridge = await readFile(path.join(scriptDir, 'demo-script.user.js'), 'utf8');

  assert.equal(bridge, bundled);
  assert.match(bridge, /GENERATED by scripts\/build-userscripts\.mjs/);
  assert.ok(bridge.includes('bannerText'), 'bridge carries the full bundled script');
});

test('buildAll output is byte-identical across runs', async (t) => {
  const { rootDir, distDir } = await createWorkspace();
  t.after(() => rm(rootDir, { recursive: true, force: true }));

  await buildAll({ rootDir, distDir });
  const first = await readFile(path.join(distDir, 'demo-script.user.js'), 'utf8');
  await buildAll({ rootDir, distDir });
  const second = await readFile(path.join(distDir, 'demo-script.user.js'), 'utf8');

  assert.equal(first, second);
});

test('buildAll fails on a lib file outside the module graph (orphan lib)', async (t) => {
  const { rootDir, scriptDir, distDir } = await createWorkspace();
  t.after(() => rm(rootDir, { recursive: true, force: true }));

  await writeFile(path.join(scriptDir, 'demo-script-orphan.lib.js'), 'export const orphan = 1;\n');

  await assert.rejects(
    () => buildAll({ rootDir, distDir }),
    /orphan lib/i,
  );
});

test('buildAll rejects entries whose metadata still declares @require or wrong dist URL', async (t) => {
  const { rootDir, scriptDir, distDir } = await createWorkspace();
  t.after(() => rm(rootDir, { recursive: true, force: true }));

  const entryPath = path.join(scriptDir, 'demo-script.entry.js');
  const original = await readFile(entryPath, 'utf8');

  await writeFile(entryPath, original.replace(
    '// @downloadURL',
    `// @require      ${RAW_BASE}/src/userscripts/demo-script/demo-script-greeting.lib.js\n// @downloadURL`,
  ));
  await assert.rejects(() => buildAll({ rootDir, distDir }), /@require/);

  await writeFile(entryPath, original.replaceAll(`/dist/demo-script.user.js`, '/dist/other.user.js'));
  await assert.rejects(() => buildAll({ rootDir, distDir }), /downloadURL|updateURL/i);
});

test('buildAll enforces SCRIPT_VERSION to match metadata @version when present', async (t) => {
  const { rootDir, scriptDir, distDir } = await createWorkspace();
  t.after(() => rm(rootDir, { recursive: true, force: true }));

  const entryPath = path.join(scriptDir, 'demo-script.entry.js');
  const original = await readFile(entryPath, 'utf8');

  await writeFile(entryPath, original.replace(
    "(function () {",
    "const SCRIPT_VERSION = '9.9.9';\n(function () {",
  ));
  await assert.rejects(() => buildAll({ rootDir, distDir }), /SCRIPT_VERSION/);
});

test('buildAll returns an empty list when no entry modules exist', async (t) => {
  const rootDir = await mkdtemp(path.join(os.tmpdir(), 'build-userscripts-empty-'));
  t.after(() => rm(rootDir, { recursive: true, force: true }));
  await mkdir(path.join(rootDir, 'src', 'userscripts', 'plain'), { recursive: true });

  const results = await buildAll({ rootDir, distDir: path.join(rootDir, 'dist') });
  assert.deepEqual(results, []);
});
