// ==UserScript==
// @name         Feishu Preview Image Export
// @namespace    https://github.com/dzshzx/custom-user-js-scripts
// @version      0.1.6
// @description  Export the main visible image from a Feishu file preview page.
// @author       dzshzx
// @match        https://mi.feishu.cn/file/*
// @grant        GM_registerMenuCommand
// @grant        GM_download
// @run-at       document-idle
// @homepageURL  https://github.com/dzshzx/custom-user-js-scripts
// @supportURL   https://github.com/dzshzx/custom-user-js-scripts/issues
// @downloadURL  https://raw.githubusercontent.com/dzshzx/custom-user-js-scripts/master/dist/feishu-preview-image-export.user.js
// @updateURL    https://raw.githubusercontent.com/dzshzx/custom-user-js-scripts/master/dist/feishu-preview-image-export.user.js
// @license      MIT
// ==/UserScript==
// GENERATED by scripts/build-userscripts.mjs — do not edit by hand.
// Sources: src/userscripts/feishu-preview-image-export/ (rebuild with `npm run build`).
(() => {
  // src/userscripts/shared/shared-tokens.lib.js
  var SAFE_COLOR_PATTERN = /^[#a-zA-Z0-9(),.\s%/+-]+$/;
  var UNSAFE_SELECTOR_CHARS = /[{};<@\\]/;
  var COLOR_SCHEME_QUERY = "(prefers-color-scheme: dark)";
  function assertSafeColor(value, name) {
    const color = String(value ?? "").trim();
    if (!color || !SAFE_COLOR_PATTERN.test(color)) {
      throw new Error(`shared-tokens: invalid ${name} color ${JSON.stringify(value)}`);
    }
    return color;
  }
  function assertSafeSelector(value) {
    const selector = String(value ?? "").trim();
    if (!selector || UNSAFE_SELECTOR_CHARS.test(selector)) {
      throw new Error(`shared-tokens: invalid rootSelector ${JSON.stringify(value)}`);
    }
    return selector;
  }
  function buildTokenCss({ rootSelector, accent, accentDark } = {}) {
    const root = assertSafeSelector(rootSelector);
    const lightAccent = assertSafeColor(accent, "accent");
    const darkAccent = accentDark == null ? lightAccent : assertSafeColor(accentDark, "accentDark");
    return `
${root} {
  --wk-surface: oklch(99.2% 0.002 250);
  --wk-surface-muted: oklch(96.8% 0.003 250);
  --wk-surface-sunken: oklch(97.8% 0.003 250);
  --wk-text: oklch(23% 0.012 250);
  --wk-text-muted: oklch(47% 0.012 250);
  --wk-border: oklch(24% 0.012 250 / 0.10);
  --wk-border-strong: oklch(24% 0.012 250 / 0.16);
  --wk-danger: oklch(52% 0.19 27);
  --wk-warning: oklch(55% 0.13 75);
  --wk-accent: ${lightAccent};
  --wk-shadow-panel: 0 24px 80px oklch(20% 0.02 250 / 0.22);
  --wk-shadow-pop: 0 8px 28px oklch(20% 0.02 250 / 0.14);
  --wk-fs-sm: 12px;
  --wk-fs-md: 13px;
  --wk-fs-lg: 15px;
  --wk-fs-xl: 20px;
  --wk-fs-hero: 28px;
  --wk-radius-ctl: 8px;
  --wk-radius-panel: 12px;
  --wk-radius-pill: 999px;
  color-scheme: light dark;
}

${root}[data-wk-theme="dark"] {
  --wk-surface: oklch(25% 0.012 250);
  --wk-surface-muted: oklch(21% 0.010 250);
  --wk-surface-sunken: oklch(23% 0.011 250);
  --wk-text: oklch(93% 0.008 250);
  --wk-text-muted: oklch(74% 0.010 250);
  --wk-border: oklch(95% 0.01 250 / 0.12);
  --wk-border-strong: oklch(95% 0.01 250 / 0.18);
  --wk-danger: oklch(68% 0.18 27);
  --wk-warning: oklch(75% 0.13 80);
  --wk-accent: ${darkAccent};
  --wk-shadow-panel: 0 24px 80px oklch(10% 0.01 250 / 0.50);
  --wk-shadow-pop: 0 8px 28px oklch(10% 0.01 250 / 0.35);
}

${root} *,
${root} *::before,
${root} *::after {
  box-sizing: border-box;
}

${root} button,
${root} input,
${root} select,
${root} textarea {
  font: inherit;
  color: inherit;
}

${root} :focus-visible {
  outline: 2px solid var(--wk-accent);
  outline-offset: 2px;
}

@media (prefers-reduced-motion: reduce) {
  ${root} *,
  ${root} *::before,
  ${root} *::after {
    animation-duration: 0.01ms !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
`.trim();
  }
  function systemPrefersDark() {
    try {
      const matchMedia = globalThis.window?.matchMedia;
      if (typeof matchMedia === "function") {
        return Boolean(matchMedia.call(globalThis.window, COLOR_SCHEME_QUERY).matches);
      }
    } catch {
    }
    return false;
  }
  function resolveTheme(detectHost) {
    if (typeof detectHost === "function") {
      try {
        const detected = detectHost();
        if (detected === "light" || detected === "dark") return detected;
      } catch {
      }
    }
    return systemPrefersDark() ? "dark" : "light";
  }
  function applyTheme(root, { detectHost, observeHost = false } = {}) {
    if (!root) {
      throw new Error("shared-tokens: applyTheme requires a root element.");
    }
    const apply = () => {
      root.dataset.wkTheme = resolveTheme(detectHost);
    };
    apply();
    let media = null;
    const onChange = () => apply();
    try {
      const matchMedia = globalThis.window?.matchMedia;
      if (typeof matchMedia === "function") {
        media = matchMedia.call(globalThis.window, COLOR_SCHEME_QUERY);
        if (typeof media?.addEventListener === "function") {
          media.addEventListener("change", onChange);
        } else if (typeof media?.addListener === "function") {
          media.addListener(onChange);
        } else {
          media = null;
        }
      }
    } catch {
      media = null;
    }
    let observer = null;
    if (observeHost) {
      try {
        const documentObject = root.ownerDocument ?? globalThis.document;
        const windowObject = documentObject?.defaultView ?? globalThis.window;
        const MutationObserverImpl = windowObject?.MutationObserver ?? globalThis.MutationObserver;
        const hostElement = documentObject?.documentElement;
        if (typeof MutationObserverImpl === "function" && hostElement && hostElement !== root) {
          observer = new MutationObserverImpl(onChange);
          observer.observe(hostElement, { attributes: true, attributeFilter: ["class", "style"] });
        }
      } catch {
        observer = null;
      }
    }
    return () => {
      if (observer) {
        observer.disconnect();
        observer = null;
      }
      if (!media) return;
      if (typeof media.removeEventListener === "function") {
        media.removeEventListener("change", onChange);
      } else if (typeof media.removeListener === "function") {
        media.removeListener(onChange);
      }
      media = null;
    };
  }

  // src/userscripts/shared/shared-icons.lib.js
  var ICON_CONTENT = {
    x: '<path d="M18 6 6 18"/><path d="m6 6 12 12"/>',
    "refresh-cw": '<path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/><path d="M21 3v5h-5"/><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"/><path d="M8 16H3v5"/>',
    settings: '<path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1-1-1.73l-.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15-.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/>',
    search: '<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>',
    "chevron-left": '<path d="m15 18-6-6 6-6"/>',
    "chevron-right": '<path d="m9 18 6-6-6-6"/>',
    "arrow-left": '<path d="m12 19-7-7 7-7"/><path d="M19 12H5"/>',
    star: '<path d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"/>',
    check: '<path d="M20 6 9 17l-5-5"/>',
    "alert-triangle": '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/><path d="M12 9v4"/><path d="M12 17h.01"/>',
    loader: '<path d="M12 2v4"/><path d="m16.2 7.8 2.9-2.9"/><path d="M18 12h4"/><path d="m16.2 16.2 2.9 2.9"/><path d="M12 18v4"/><path d="m4.9 19.1 2.9-2.9"/><path d="M2 12h4"/><path d="m4.9 4.9 2.9 2.9"/>'
  };
  var ICON_NAMES = Object.keys(ICON_CONTENT);
  function toPositiveNumber(value, name) {
    const number = Number(value);
    if (!Number.isFinite(number) || number <= 0) {
      throw new Error(`shared-icons: ${name} must be a positive number, got ${JSON.stringify(value)}`);
    }
    return number;
  }
  function iconSvg(name, { size = 16, strokeWidth = 2 } = {}) {
    const content = ICON_CONTENT[name];
    if (!content) {
      throw new Error(`shared-icons: unknown icon "${name}". Available: ${ICON_NAMES.join(", ")}`);
    }
    const resolvedSize = toPositiveNumber(size, "size");
    const resolvedStrokeWidth = toPositiveNumber(strokeWidth, "strokeWidth");
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${resolvedStrokeWidth}" stroke-linecap="round" stroke-linejoin="round" width="${resolvedSize}" height="${resolvedSize}" class="wk-icon wk-icon-${name}" aria-hidden="true" focusable="false">${content}</svg>`;
  }

  // src/userscripts/shared/shared-toast.lib.js
  var TOAST_LIMIT = 3;
  var DEFAULT_DURATION_MS = 4e3;
  var ERROR_DURATION_MS = 6e3;
  var EXIT_ANIMATION_MS = 160;
  var TONE_ICONS = {
    success: "check",
    error: "alert-triangle",
    progress: "loader"
  };
  var TOAST_CSS = `
.wk-toasts {
  position: fixed;
  right: 16px;
  bottom: 16px;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 8px;
  font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
  pointer-events: none;
}

.wk-toast {
  display: flex;
  align-items: center;
  gap: 8px;
  max-width: min(360px, calc(100vw - 32px));
  padding: 10px 14px;
  border: 1px solid var(--wk-border);
  border-radius: var(--wk-radius-ctl);
  background: var(--wk-surface);
  color: var(--wk-text);
  box-shadow: var(--wk-shadow-pop);
  font-size: var(--wk-fs-md);
  line-height: 1.4;
  pointer-events: auto;
  animation: wk-toast-in 160ms ease-out;
  transition: opacity 160ms ease, transform 160ms ease;
}

.wk-toast.is-leaving {
  opacity: 0;
  transform: translateY(8px);
}

.wk-toast-icon {
  display: inline-flex;
  flex: none;
}

.wk-toast[data-tone="success"] .wk-toast-icon {
  color: var(--wk-accent);
}

.wk-toast[data-tone="error"] .wk-toast-icon {
  color: var(--wk-danger);
}

.wk-toast[data-tone="progress"] .wk-toast-icon {
  color: var(--wk-text-muted);
}

.wk-toast .wk-spin {
  animation: wk-spin 0.9s linear infinite;
}

@keyframes wk-toast-in {
  from {
    opacity: 0;
    transform: translateY(8px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes wk-spin {
  to {
    transform: rotate(360deg);
  }
}

@media (prefers-reduced-motion: reduce) {
  .wk-toast {
    animation: none;
    transition: none;
  }

  .wk-toast .wk-spin {
    animation: none;
  }
}
`.trim();
  function createToaster({ root } = {}) {
    if (!root?.append) {
      throw new Error("shared-toast: createToaster requires a root element.");
    }
    const documentObject = root.ownerDocument ?? globalThis.document;
    if (!documentObject?.createElement) {
      throw new Error("shared-toast: root must expose ownerDocument.");
    }
    const timers = /* @__PURE__ */ new Set();
    const container = documentObject.createElement("div");
    container.className = "wk-toasts";
    container.setAttribute("role", "status");
    container.setAttribute("aria-live", "polite");
    root.append(container);
    function schedule(callback, delay) {
      const timer = setTimeout(() => {
        timers.delete(timer);
        callback();
      }, delay);
      timers.add(timer);
    }
    function dismiss(toast) {
      if (!toast.parentNode) return;
      toast.classList.add("is-leaving");
      schedule(() => toast.remove(), EXIT_ANIMATION_MS);
    }
    function enforceLimit() {
      while (container.children.length > TOAST_LIMIT) {
        container.firstElementChild?.remove();
      }
    }
    function setTone(toast, tone) {
      toast.dataset.tone = tone;
      const iconNode = toast.querySelector(".wk-toast-icon");
      const iconName = TONE_ICONS[tone];
      if (iconName) {
        iconNode.innerHTML = iconSvg(iconName);
        iconNode.classList.toggle("wk-spin", tone === "progress");
        iconNode.hidden = false;
      } else {
        iconNode.innerHTML = "";
        iconNode.classList.remove("wk-spin");
        iconNode.hidden = true;
      }
    }
    function setMessage(toast, message) {
      toast.querySelector(".wk-toast-message").textContent = String(message ?? "");
    }
    function buildToast({ message, tone }) {
      const toast = documentObject.createElement("div");
      toast.className = "wk-toast";
      const iconNode = documentObject.createElement("span");
      iconNode.className = "wk-toast-icon";
      const messageNode = documentObject.createElement("span");
      messageNode.className = "wk-toast-message";
      toast.append(iconNode, messageNode);
      setTone(toast, tone);
      setMessage(toast, message);
      return toast;
    }
    function autoDismiss(toast, duration) {
      if (Number.isFinite(duration) && duration > 0) {
        schedule(() => dismiss(toast), duration);
      }
    }
    function show({ message, tone = "info", duration } = {}) {
      const resolvedTone = ["success", "error", "info"].includes(tone) ? tone : "info";
      const toast = buildToast({ message, tone: resolvedTone });
      container.append(toast);
      enforceLimit();
      autoDismiss(toast, duration ?? (resolvedTone === "error" ? ERROR_DURATION_MS : DEFAULT_DURATION_MS));
      return toast;
    }
    function showProgress({ message } = {}) {
      const toast = buildToast({ message, tone: "progress" });
      container.append(toast);
      enforceLimit();
      let settled = false;
      function settle(tone, nextMessage, duration) {
        if (settled) return;
        settled = true;
        if (nextMessage != null) setMessage(toast, nextMessage);
        setTone(toast, tone);
        autoDismiss(toast, duration);
      }
      return {
        update(nextMessage) {
          if (!settled) setMessage(toast, nextMessage);
        },
        done(successMessage) {
          settle("success", successMessage, DEFAULT_DURATION_MS);
        },
        fail(errorMessage) {
          settle("error", errorMessage, ERROR_DURATION_MS);
        }
      };
    }
    function destroy() {
      for (const timer of timers) clearTimeout(timer);
      timers.clear();
      container.remove();
    }
    return {
      cssText: TOAST_CSS,
      show,
      showProgress,
      destroy
    };
  }

  // node_modules/filename-reserved-regex/index.js
  function filenameReservedRegex() {
    return /[<>:"/\\|?*\u0000-\u001F]|[. ]$/g;
  }
  function windowsReservedNameRegex() {
    return /^(?:con|prn|aux|nul|conin\$|conout\$|com[\d¹²³]|lpt[\d¹²³]) *(?:\..*)?$/i;
  }

  // node_modules/filenamify/filenamify.js
  var MAX_FILENAME_LENGTH = 100;
  var reRelativePath = /^\.+(\\|\/)|^\.+$/;
  var reTrailingDotsAndSpaces = /[. ]+$/;
  var reTrailingSpaces = / +$/;
  var reWindowsReservedName = windowsReservedNameRegex();
  var reControlChars = /[\p{Control}\p{Format}\p{Zl}\p{Zp}\uFFF0-\uFFFF]/gu;
  var reControlCharsTest = /[\p{Control}\p{Format}\p{Zl}\p{Zp}\uFFF0-\uFFFF]/u;
  var isZeroWidthJoiner = (char) => char === "‍";
  var reRepeatedReservedCharacters = /([<>:"/\\|?*\u0000-\u001F]){2,}/g;
  var reReplacementReservedCharacters = /[<>:"/\\|?*\u0000-\u001F]/;
  var reUnicodeWhitespace = /[\t\n\r\u00A0\u1680\u2000-\u200A\u202F\u205F\u3000]+/g;
  var segmenter;
  function getSegmenter() {
    segmenter ??= new Intl.Segmenter(void 0, { granularity: "grapheme" });
    return segmenter;
  }
  function truncateFilename(filename, maxLength) {
    if (filename.length <= maxLength) {
      return filename;
    }
    const extensionIndex = filename.lastIndexOf(".");
    if (extensionIndex === -1) {
      return truncateByGraphemeBudget(filename, maxLength);
    }
    const base = filename.slice(0, extensionIndex);
    const extension = filename.slice(extensionIndex);
    const baseBudget = Math.max(0, maxLength - extension.length);
    const truncatedBase = truncateByGraphemeBudget(base, baseBudget);
    return truncatedBase.replace(reTrailingSpaces, "") + extension;
  }
  function ensureNonWindowsReservedName(filename, replacement) {
    if (!reWindowsReservedName.test(filename)) {
      return filename;
    }
    const extensionIndex = filename.indexOf(".");
    const base = extensionIndex === -1 ? filename : filename.slice(0, extensionIndex);
    const baseWithoutTrailingSpaces = base.replace(reTrailingSpaces, "");
    const extension = extensionIndex === -1 ? "" : filename.slice(extensionIndex);
    const candidate = (baseWithoutTrailingSpaces + replacement + extension).replace(reTrailingDotsAndSpaces, "");
    return reWindowsReservedName.test(candidate) ? baseWithoutTrailingSpaces + "!" + extension : candidate;
  }
  function filenamify(string, options = {}) {
    if (typeof string !== "string") {
      throw new TypeError("Expected a string");
    }
    const replacement = options.replacement ?? "!";
    const hasReservedChars = reReplacementReservedCharacters.test(replacement);
    const hasControlChars = [...replacement].some((char) => reControlCharsTest.test(char) && !isZeroWidthJoiner(char));
    if (hasReservedChars || hasControlChars) {
      throw new Error("Replacement string cannot contain reserved filename characters");
    }
    string = string.normalize("NFC");
    string = string.replaceAll(reUnicodeWhitespace, " ");
    if (replacement.length > 0) {
      string = string.replaceAll(reRepeatedReservedCharacters, "$1");
    }
    string = string.replace(reTrailingDotsAndSpaces, "");
    string = string.replace(reRelativePath, () => replacement);
    string = string.replace(filenameReservedRegex(), () => replacement);
    string = string.replaceAll(reControlChars, (char) => isZeroWidthJoiner(char) ? char : replacement);
    string = string.replace(reTrailingDotsAndSpaces, "");
    if (string.length === 0) {
      string = replacement.replace(reTrailingDotsAndSpaces, "");
      if (string.length === 0 && replacement.length > 0) {
        string = "!";
      }
    }
    const allowedLength = typeof options.maxLength === "number" ? options.maxLength : MAX_FILENAME_LENGTH;
    string = truncateFilename(string, allowedLength);
    string = string.replace(reTrailingDotsAndSpaces, "");
    string = ensureNonWindowsReservedName(string, replacement);
    return string;
  }
  function truncateByGraphemeBudget(input, budget) {
    if (input.length <= budget) {
      return input;
    }
    let count = 0;
    let output = "";
    for (const { segment } of getSegmenter().segment(input)) {
      const next = count + segment.length;
      if (next > budget) {
        break;
      }
      output += segment;
      count = next;
    }
    return output;
  }

  // node_modules/mime/dist/types/standard.js
  var types = {
    "application/andrew-inset": ["ez"],
    "application/appinstaller": ["appinstaller"],
    "application/applixware": ["aw"],
    "application/appx": ["appx"],
    "application/appxbundle": ["appxbundle"],
    "application/atom+xml": ["atom"],
    "application/atomcat+xml": ["atomcat"],
    "application/atomdeleted+xml": ["atomdeleted"],
    "application/atomsvc+xml": ["atomsvc"],
    "application/atsc-dwd+xml": ["dwd"],
    "application/atsc-held+xml": ["held"],
    "application/atsc-rsat+xml": ["rsat"],
    "application/automationml-aml+xml": ["aml"],
    "application/automationml-amlx+zip": ["amlx"],
    "application/bdoc": ["bdoc"],
    "application/calendar+xml": ["xcs"],
    "application/ccxml+xml": ["ccxml"],
    "application/cdfx+xml": ["cdfx"],
    "application/cdmi-capability": ["cdmia"],
    "application/cdmi-container": ["cdmic"],
    "application/cdmi-domain": ["cdmid"],
    "application/cdmi-object": ["cdmio"],
    "application/cdmi-queue": ["cdmiq"],
    "application/cpl+xml": ["cpl"],
    "application/cu-seeme": ["cu"],
    "application/cwl": ["cwl"],
    "application/dash+xml": ["mpd"],
    "application/dash-patch+xml": ["mpp"],
    "application/davmount+xml": ["davmount"],
    "application/dicom": ["dcm"],
    "application/docbook+xml": ["dbk"],
    "application/dssc+der": ["dssc"],
    "application/dssc+xml": ["xdssc"],
    "application/ecmascript": ["ecma"],
    "application/emma+xml": ["emma"],
    "application/emotionml+xml": ["emotionml"],
    "application/epub+zip": ["epub"],
    "application/exi": ["exi"],
    "application/express": ["exp"],
    "application/fdf": ["fdf"],
    "application/fdt+xml": ["fdt"],
    "application/font-tdpfr": ["pfr"],
    "application/geo+json": ["geojson"],
    "application/gml+xml": ["gml"],
    "application/gpx+xml": ["gpx"],
    "application/gxf": ["gxf"],
    "application/gzip": ["gz"],
    "application/hjson": ["hjson"],
    "application/hyperstudio": ["stk"],
    "application/inkml+xml": ["ink", "inkml"],
    "application/ipfix": ["ipfix"],
    "application/its+xml": ["its"],
    "application/java-archive": ["jar", "war", "ear"],
    "application/java-serialized-object": ["ser"],
    "application/java-vm": ["class"],
    "application/javascript": ["*js"],
    "application/json": ["json", "map"],
    "application/json5": ["json5"],
    "application/jsonml+json": ["jsonml"],
    "application/ld+json": ["jsonld"],
    "application/lgr+xml": ["lgr"],
    "application/lost+xml": ["lostxml"],
    "application/mac-binhex40": ["hqx"],
    "application/mac-compactpro": ["cpt"],
    "application/mads+xml": ["mads"],
    "application/manifest+json": ["webmanifest"],
    "application/marc": ["mrc"],
    "application/marcxml+xml": ["mrcx"],
    "application/mathematica": ["ma", "nb", "mb"],
    "application/mathml+xml": ["mathml"],
    "application/mbox": ["mbox"],
    "application/media-policy-dataset+xml": ["mpf"],
    "application/mediaservercontrol+xml": ["mscml"],
    "application/metalink+xml": ["metalink"],
    "application/metalink4+xml": ["meta4"],
    "application/mets+xml": ["mets"],
    "application/mmt-aei+xml": ["maei"],
    "application/mmt-usd+xml": ["musd"],
    "application/mods+xml": ["mods"],
    "application/mp21": ["m21", "mp21"],
    "application/mp4": ["*mp4", "*mpg4", "mp4s", "m4p"],
    "application/msix": ["msix"],
    "application/msixbundle": ["msixbundle"],
    "application/msword": ["doc", "dot"],
    "application/mxf": ["mxf"],
    "application/n-quads": ["nq"],
    "application/n-triples": ["nt"],
    "application/node": ["cjs"],
    "application/octet-stream": [
      "bin",
      "dms",
      "lrf",
      "mar",
      "so",
      "dist",
      "distz",
      "pkg",
      "bpk",
      "dump",
      "elc",
      "deploy",
      "exe",
      "dll",
      "deb",
      "dmg",
      "iso",
      "img",
      "msi",
      "msp",
      "msm",
      "buffer"
    ],
    "application/oda": ["oda"],
    "application/oebps-package+xml": ["opf"],
    "application/ogg": ["ogx"],
    "application/omdoc+xml": ["omdoc"],
    "application/onenote": [
      "onetoc",
      "onetoc2",
      "onetmp",
      "onepkg",
      "one",
      "onea"
    ],
    "application/oxps": ["oxps"],
    "application/p2p-overlay+xml": ["relo"],
    "application/patch-ops-error+xml": ["xer"],
    "application/pdf": ["pdf"],
    "application/pgp-encrypted": ["pgp"],
    "application/pgp-keys": ["asc"],
    "application/pgp-signature": ["sig", "*asc"],
    "application/pics-rules": ["prf"],
    "application/pkcs10": ["p10"],
    "application/pkcs7-mime": ["p7m", "p7c"],
    "application/pkcs7-signature": ["p7s"],
    "application/pkcs8": ["p8"],
    "application/pkix-attr-cert": ["ac"],
    "application/pkix-cert": ["cer"],
    "application/pkix-crl": ["crl"],
    "application/pkix-pkipath": ["pkipath"],
    "application/pkixcmp": ["pki"],
    "application/pls+xml": ["pls"],
    "application/postscript": ["ai", "eps", "ps"],
    "application/provenance+xml": ["provx"],
    "application/pskc+xml": ["pskcxml"],
    "application/raml+yaml": ["raml"],
    "application/rdf+xml": ["rdf", "owl"],
    "application/reginfo+xml": ["rif"],
    "application/relax-ng-compact-syntax": ["rnc"],
    "application/resource-lists+xml": ["rl"],
    "application/resource-lists-diff+xml": ["rld"],
    "application/rls-services+xml": ["rs"],
    "application/route-apd+xml": ["rapd"],
    "application/route-s-tsid+xml": ["sls"],
    "application/route-usd+xml": ["rusd"],
    "application/rpki-ghostbusters": ["gbr"],
    "application/rpki-manifest": ["mft"],
    "application/rpki-roa": ["roa"],
    "application/rsd+xml": ["rsd"],
    "application/rss+xml": ["rss"],
    "application/rtf": ["rtf"],
    "application/sbml+xml": ["sbml"],
    "application/scvp-cv-request": ["scq"],
    "application/scvp-cv-response": ["scs"],
    "application/scvp-vp-request": ["spq"],
    "application/scvp-vp-response": ["spp"],
    "application/sdp": ["sdp"],
    "application/senml+xml": ["senmlx"],
    "application/sensml+xml": ["sensmlx"],
    "application/set-payment-initiation": ["setpay"],
    "application/set-registration-initiation": ["setreg"],
    "application/shf+xml": ["shf"],
    "application/sieve": ["siv", "sieve"],
    "application/smil+xml": ["smi", "smil"],
    "application/sparql-query": ["rq"],
    "application/sparql-results+xml": ["srx"],
    "application/sql": ["sql"],
    "application/srgs": ["gram"],
    "application/srgs+xml": ["grxml"],
    "application/sru+xml": ["sru"],
    "application/ssdl+xml": ["ssdl"],
    "application/ssml+xml": ["ssml"],
    "application/swid+xml": ["swidtag"],
    "application/tei+xml": ["tei", "teicorpus"],
    "application/thraud+xml": ["tfi"],
    "application/timestamped-data": ["tsd"],
    "application/toml": ["toml"],
    "application/trig": ["trig"],
    "application/ttml+xml": ["ttml"],
    "application/ubjson": ["ubj"],
    "application/urc-ressheet+xml": ["rsheet"],
    "application/urc-targetdesc+xml": ["td"],
    "application/voicexml+xml": ["vxml"],
    "application/wasm": ["wasm"],
    "application/watcherinfo+xml": ["wif"],
    "application/widget": ["wgt"],
    "application/winhlp": ["hlp"],
    "application/wsdl+xml": ["wsdl"],
    "application/wspolicy+xml": ["wspolicy"],
    "application/xaml+xml": ["xaml"],
    "application/xcap-att+xml": ["xav"],
    "application/xcap-caps+xml": ["xca"],
    "application/xcap-diff+xml": ["xdf"],
    "application/xcap-el+xml": ["xel"],
    "application/xcap-ns+xml": ["xns"],
    "application/xenc+xml": ["xenc"],
    "application/xfdf": ["xfdf"],
    "application/xhtml+xml": ["xhtml", "xht"],
    "application/xliff+xml": ["xlf"],
    "application/xml": ["xml", "xsl", "xsd", "rng"],
    "application/xml-dtd": ["dtd"],
    "application/xop+xml": ["xop"],
    "application/xproc+xml": ["xpl"],
    "application/xslt+xml": ["*xsl", "xslt"],
    "application/xspf+xml": ["xspf"],
    "application/xv+xml": ["mxml", "xhvml", "xvml", "xvm"],
    "application/yang": ["yang"],
    "application/yin+xml": ["yin"],
    "application/zip": ["zip"],
    "application/zip+dotlottie": ["lottie"],
    "audio/3gpp": ["*3gpp"],
    "audio/aac": ["adts", "aac"],
    "audio/adpcm": ["adp"],
    "audio/amr": ["amr"],
    "audio/basic": ["au", "snd"],
    "audio/midi": ["mid", "midi", "kar", "rmi"],
    "audio/mobile-xmf": ["mxmf"],
    "audio/mp3": ["*mp3"],
    "audio/mp4": ["m4a", "mp4a", "m4b"],
    "audio/mpeg": ["mpga", "mp2", "mp2a", "mp3", "m2a", "m3a"],
    "audio/ogg": ["oga", "ogg", "spx", "opus"],
    "audio/s3m": ["s3m"],
    "audio/silk": ["sil"],
    "audio/wav": ["wav"],
    "audio/wave": ["*wav"],
    "audio/webm": ["weba"],
    "audio/xm": ["xm"],
    "font/collection": ["ttc"],
    "font/otf": ["otf"],
    "font/ttf": ["ttf"],
    "font/woff": ["woff"],
    "font/woff2": ["woff2"],
    "image/aces": ["exr"],
    "image/apng": ["apng"],
    "image/avci": ["avci"],
    "image/avcs": ["avcs"],
    "image/avif": ["avif"],
    "image/bmp": ["bmp", "dib"],
    "image/cgm": ["cgm"],
    "image/dicom-rle": ["drle"],
    "image/dpx": ["dpx"],
    "image/emf": ["emf"],
    "image/fits": ["fits"],
    "image/g3fax": ["g3"],
    "image/gif": ["gif"],
    "image/heic": ["heic"],
    "image/heic-sequence": ["heics"],
    "image/heif": ["heif"],
    "image/heif-sequence": ["heifs"],
    "image/hej2k": ["hej2"],
    "image/ief": ["ief"],
    "image/jaii": ["jaii"],
    "image/jais": ["jais"],
    "image/jls": ["jls"],
    "image/jp2": ["jp2", "jpg2"],
    "image/jpeg": ["jpg", "jpeg", "jpe"],
    "image/jph": ["jph"],
    "image/jphc": ["jhc"],
    "image/jpm": ["jpm", "jpgm"],
    "image/jpx": ["jpx", "jpf"],
    "image/jxl": ["jxl"],
    "image/jxr": ["jxr"],
    "image/jxra": ["jxra"],
    "image/jxrs": ["jxrs"],
    "image/jxs": ["jxs"],
    "image/jxsc": ["jxsc"],
    "image/jxsi": ["jxsi"],
    "image/jxss": ["jxss"],
    "image/ktx": ["ktx"],
    "image/ktx2": ["ktx2"],
    "image/pjpeg": ["jfif"],
    "image/png": ["png"],
    "image/sgi": ["sgi"],
    "image/svg+xml": ["svg", "svgz"],
    "image/t38": ["t38"],
    "image/tiff": ["tif", "tiff"],
    "image/tiff-fx": ["tfx"],
    "image/webp": ["webp"],
    "image/wmf": ["wmf"],
    "message/disposition-notification": ["disposition-notification"],
    "message/global": ["u8msg"],
    "message/global-delivery-status": ["u8dsn"],
    "message/global-disposition-notification": ["u8mdn"],
    "message/global-headers": ["u8hdr"],
    "message/rfc822": ["eml", "mime", "mht", "mhtml"],
    "model/3mf": ["3mf"],
    "model/gltf+json": ["gltf"],
    "model/gltf-binary": ["glb"],
    "model/iges": ["igs", "iges"],
    "model/jt": ["jt"],
    "model/mesh": ["msh", "mesh", "silo"],
    "model/mtl": ["mtl"],
    "model/obj": ["obj"],
    "model/prc": ["prc"],
    "model/step": ["step", "stp", "stpnc", "p21", "210"],
    "model/step+xml": ["stpx"],
    "model/step+zip": ["stpz"],
    "model/step-xml+zip": ["stpxz"],
    "model/stl": ["stl"],
    "model/u3d": ["u3d"],
    "model/vrml": ["wrl", "vrml"],
    "model/x3d+binary": ["*x3db", "x3dbz"],
    "model/x3d+fastinfoset": ["x3db"],
    "model/x3d+vrml": ["*x3dv", "x3dvz"],
    "model/x3d+xml": ["x3d", "x3dz"],
    "model/x3d-vrml": ["x3dv"],
    "text/cache-manifest": ["appcache", "manifest"],
    "text/calendar": ["ics", "ifb"],
    "text/coffeescript": ["coffee", "litcoffee"],
    "text/css": ["css"],
    "text/csv": ["csv"],
    "text/html": ["html", "htm", "shtml"],
    "text/jade": ["jade"],
    "text/javascript": ["js", "mjs"],
    "text/jsx": ["jsx"],
    "text/less": ["less"],
    "text/markdown": ["md", "markdown"],
    "text/mathml": ["mml"],
    "text/mdx": ["mdx"],
    "text/n3": ["n3"],
    "text/plain": ["txt", "text", "conf", "def", "list", "log", "in", "ini"],
    "text/richtext": ["rtx"],
    "text/rtf": ["*rtf"],
    "text/sgml": ["sgml", "sgm"],
    "text/shex": ["shex"],
    "text/slim": ["slim", "slm"],
    "text/spdx": ["spdx"],
    "text/stylus": ["stylus", "styl"],
    "text/tab-separated-values": ["tsv"],
    "text/troff": ["t", "tr", "roff", "man", "me", "ms"],
    "text/turtle": ["ttl"],
    "text/uri-list": ["uri", "uris", "urls"],
    "text/vcard": ["vcard"],
    "text/vtt": ["vtt"],
    "text/wgsl": ["wgsl"],
    "text/xml": ["*xml"],
    "text/yaml": ["yaml", "yml"],
    "video/3gpp": ["3gp", "3gpp"],
    "video/3gpp2": ["3g2"],
    "video/h261": ["h261"],
    "video/h263": ["h263"],
    "video/h264": ["h264"],
    "video/iso.segment": ["m4s"],
    "video/jpeg": ["jpgv"],
    "video/jpm": ["*jpm", "*jpgm"],
    "video/mj2": ["mj2", "mjp2"],
    "video/mp2t": ["ts", "m2t", "m2ts", "mts"],
    "video/mp4": ["mp4", "mp4v", "mpg4"],
    "video/mpeg": ["mpeg", "mpg", "mpe", "m1v", "m2v"],
    "video/ogg": ["ogv"],
    "video/quicktime": ["qt", "mov"],
    "video/webm": ["webm"]
  };
  Object.freeze(types);
  var standard_default = types;

  // node_modules/mime/dist/src/Mime.js
  var __classPrivateFieldGet = function(receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
  };
  var _Mime_extensionToType;
  var _Mime_typeToExtension;
  var _Mime_typeToExtensions;
  var Mime = class {
    constructor(...args) {
      _Mime_extensionToType.set(this, /* @__PURE__ */ new Map());
      _Mime_typeToExtension.set(this, /* @__PURE__ */ new Map());
      _Mime_typeToExtensions.set(this, /* @__PURE__ */ new Map());
      for (const arg of args) {
        this.define(arg);
      }
    }
    define(typeMap, force = false) {
      for (let [type, extensions] of Object.entries(typeMap)) {
        type = type.toLowerCase();
        extensions = extensions.map((ext) => ext.toLowerCase());
        if (!__classPrivateFieldGet(this, _Mime_typeToExtensions, "f").has(type)) {
          __classPrivateFieldGet(this, _Mime_typeToExtensions, "f").set(type, /* @__PURE__ */ new Set());
        }
        const allExtensions = __classPrivateFieldGet(this, _Mime_typeToExtensions, "f").get(type);
        let first = true;
        for (let extension of extensions) {
          const starred = extension.startsWith("*");
          extension = starred ? extension.slice(1) : extension;
          allExtensions?.add(extension);
          if (first) {
            __classPrivateFieldGet(this, _Mime_typeToExtension, "f").set(type, extension);
          }
          first = false;
          if (starred)
            continue;
          const currentType = __classPrivateFieldGet(this, _Mime_extensionToType, "f").get(extension);
          if (currentType && currentType != type && !force) {
            throw new Error(`"${type} -> ${extension}" conflicts with "${currentType} -> ${extension}". Pass \`force=true\` to override this definition.`);
          }
          __classPrivateFieldGet(this, _Mime_extensionToType, "f").set(extension, type);
        }
      }
      return this;
    }
    getType(path) {
      if (typeof path !== "string")
        return null;
      const last = path.replace(/^.*[/\\]/s, "").toLowerCase();
      const ext = last.replace(/^.*\./s, "").toLowerCase();
      const hasPath = last.length < path.length;
      const hasDot = ext.length < last.length - 1;
      if (!hasDot && hasPath)
        return null;
      return __classPrivateFieldGet(this, _Mime_extensionToType, "f").get(ext) ?? null;
    }
    getExtension(type) {
      if (typeof type !== "string")
        return null;
      type = type?.split?.(";")[0];
      return (type && __classPrivateFieldGet(this, _Mime_typeToExtension, "f").get(type.trim().toLowerCase())) ?? null;
    }
    getAllExtensions(type) {
      if (typeof type !== "string")
        return null;
      return __classPrivateFieldGet(this, _Mime_typeToExtensions, "f").get(type.toLowerCase()) ?? null;
    }
    _freeze() {
      this.define = () => {
        throw new Error("define() not allowed for built-in Mime objects. See https://github.com/broofa/mime/blob/main/README.md#custom-mime-instances");
      };
      Object.freeze(this);
      for (const extensions of __classPrivateFieldGet(this, _Mime_typeToExtensions, "f").values()) {
        Object.freeze(extensions);
      }
      return this;
    }
    _getTestState() {
      return {
        types: __classPrivateFieldGet(this, _Mime_extensionToType, "f"),
        extensions: __classPrivateFieldGet(this, _Mime_typeToExtension, "f")
      };
    }
  };
  _Mime_extensionToType = /* @__PURE__ */ new WeakMap(), _Mime_typeToExtension = /* @__PURE__ */ new WeakMap(), _Mime_typeToExtensions = /* @__PURE__ */ new WeakMap();
  var Mime_default = Mime;

  // node_modules/mime/dist/src/index_lite.js
  var index_lite_default = new Mime_default(standard_default)._freeze();

  // src/userscripts/feishu-preview-image-export/feishu-preview-image-export-extraction.lib.js
  function readPreviewImage(options = {}, environment = {}) {
    const profile = options.profile;
    const mode = options.mode || "read";
    if (profile !== "userscript-v1" && profile !== "cli-v1") {
      throw new Error(`Unknown image profile: ${profile}`);
    }
    if (mode !== "read" && mode !== "inspect") {
      throw new Error(`Unknown image mode: ${mode}`);
    }
    const attachDiagnostic = (cause, code, phase) => {
      const error = cause instanceof Error ? cause : new Error(String(cause));
      try {
        error.code = code;
        error.phase = phase;
      } catch {
        const wrapped = new Error(error.message, { cause: error });
        wrapped.code = code;
        wrapped.phase = phase;
        return wrapped;
      }
      return error;
    };
    const host = typeof globalThis === "object" && globalThis ? globalThis : {};
    const documentObject = environment.documentObject || host.document;
    const imageNodes = profile === "userscript-v1" ? [...documentObject.images || documentObject.getElementsByTagName("img")] : [...documentObject.querySelectorAll("img")];
    const items = imageNodes.map((img, index) => {
      const rect = img.getBoundingClientRect();
      const rawWidth = rect.width;
      const rawHeight = rect.height;
      const width = Math.round(rawWidth);
      const height = Math.round(rawHeight);
      const area = profile === "userscript-v1" ? width * height : rawWidth * rawHeight;
      return {
        src: profile === "userscript-v1" ? img.currentSrc || img.src || "" : img.getAttribute("src") || "",
        width,
        height,
        area,
        index
      };
    }).filter(
      (item) => profile === "userscript-v1" ? item.width > 0 && item.height > 0 && item.area >= 2e4 : item.area > 2e4
    ).sort((left, right) => right.area - left.area || left.index - right.index).map(({ index: _index, ...item }) => item);
    if (mode === "inspect") {
      return { kind: "candidates", items };
    }
    return (async () => {
      if (!items.length) {
        return { kind: "empty", reason: "no-candidate" };
      }
      const target = items[0];
      const source = target.src;
      if (profile === "userscript-v1" && !source) {
        throw attachDiagnostic(new Error("Image source is empty"), "FEISHU_IMAGE_SOURCE_EMPTY", "source");
      }
      if (source.startsWith("data:")) {
        const match = source.match(/^data:([^;]+);base64,(.+)$/);
        if (!match) {
          if (profile === "cli-v1") {
            return { kind: "empty", reason: "invalid-data-url" };
          }
          throw attachDiagnostic(new Error("Unsupported data URL format"), "FEISHU_IMAGE_INVALID_DATA_URL", "data-url");
        }
        return {
          kind: "image",
          mime: match[1],
          width: target.width,
          height: target.height,
          mode: "data-url",
          payload: profile === "userscript-v1" ? { encoding: "data-url", data: source } : { encoding: "base64", data: match[2] }
        };
      }
      const fetcher = environment.fetchImpl || host.fetch?.bind(host);
      if (typeof fetcher !== "function") {
        throw attachDiagnostic(new Error("fetch unavailable"), "FEISHU_IMAGE_FETCH_FAILED", "fetch");
      }
      let response;
      try {
        response = profile === "userscript-v1" ? await fetcher(source, { credentials: "include" }) : await fetcher(source);
      } catch (error) {
        throw attachDiagnostic(error, "FEISHU_IMAGE_FETCH_FAILED", "fetch");
      }
      if (!response.ok) {
        throw attachDiagnostic(
          new Error(`Failed to fetch image: ${response.status} ${response.statusText}`),
          "FEISHU_IMAGE_FETCH_FAILED",
          "fetch"
        );
      }
      if (profile === "userscript-v1") {
        let blob;
        try {
          blob = await response.blob();
        } catch (error) {
          throw attachDiagnostic(error, "FEISHU_IMAGE_BLOB_READ_FAILED", "blob-read");
        }
        const FileReaderCtor = environment.FileReaderCtor || host.FileReader;
        let data2;
        try {
          data2 = await new Promise((resolve, reject) => {
            const reader = new FileReaderCtor();
            reader.onload = () => resolve(String(reader.result || ""));
            reader.onerror = () => reject(reader.error || new Error("Failed to read blob"));
            reader.readAsDataURL(blob);
          });
        } catch (error) {
          throw attachDiagnostic(error, "FEISHU_IMAGE_BLOB_READ_FAILED", "blob-read");
        }
        return {
          kind: "image",
          mime: blob.type || "application/octet-stream",
          width: target.width,
          height: target.height,
          mode: "fetched",
          payload: { encoding: "data-url", data: data2 }
        };
      }
      let bytes;
      try {
        bytes = new Uint8Array(await response.arrayBuffer());
      } catch (error) {
        throw attachDiagnostic(error, "FEISHU_IMAGE_BLOB_READ_FAILED", "blob-read");
      }
      let binary = "";
      for (const byte of bytes) {
        binary += String.fromCharCode(byte);
      }
      const encode = environment.btoaImpl || host.btoa?.bind(host);
      let data;
      try {
        data = encode(binary);
      } catch (error) {
        throw attachDiagnostic(error, "FEISHU_IMAGE_ENCODE_FAILED", "encode");
      }
      return {
        kind: "image",
        mime: response.headers.get("content-type") || "application/octet-stream",
        width: target.width,
        height: target.height,
        mode: "fetched",
        payload: { encoding: "base64", data }
      };
    })();
  }

  // src/userscripts/feishu-preview-image-export/feishu-preview-image-export-logic.lib.js
  var LIB_NAME = "FeishuPreviewImageExportLogicLib";
  function sanitizeFilePart(value, fallback) {
    const text = String(value || "").trim();
    return text ? filenamify(text, { replacement: "-" }) : fallback;
  }
  function extensionFromMime(type) {
    return index_lite_default.getExtension(String(type || "")) || "bin";
  }
  function toUserMessage(error) {
    const text = error instanceof Error ? error.message : String(error);
    const httpMatch = /^Failed to fetch image: (\d+)/.exec(text);
    if (httpMatch) {
      return `图片拉取失败（HTTP ${httpMatch[1]}），请确认已登录飞书或稍后重试。`;
    }
    if (text.includes("Unsupported data URL format")) {
      return "图片地址格式不支持，无法导出。";
    }
    if (text.includes("Image source is empty")) {
      return "未读取到图片地址，请刷新页面后重试。";
    }
    if (text.includes("GM_download timed out")) {
      return "下载超时，请重试。";
    }
    if (text.includes("GM_download failed")) {
      return "浏览器下载失败，请重试。";
    }
    if (text.includes("Failed to read blob")) {
      return "图片数据读取失败，请重试。";
    }
    return `导出失败：${text}`;
  }
  function createImageExportRuntime({ documentObject, fetchImpl, gmDownload } = {}) {
    if (!documentObject) throw new Error(`${LIB_NAME}: documentObject is required.`);
    function getDocumentTitle() {
      const raw = documentObject.title.replace(/\s*-\s*飞书云文档\s*$/u, "").trim();
      return sanitizeFilePart(raw, "feishu-image");
    }
    function getVisibleImages() {
      return readPreviewImage({ profile: "userscript-v1", mode: "inspect" }, { documentObject }).items;
    }
    function fallbackDownload(url, filename) {
      const anchor = documentObject.createElement("a");
      anchor.href = url;
      anchor.download = filename;
      anchor.rel = "noopener";
      documentObject.body.appendChild(anchor);
      anchor.click();
      anchor.remove();
    }
    function gmDownloadPromise(url, filename) {
      return new Promise((resolve, reject) => {
        gmDownload({
          url,
          name: filename,
          saveAs: true,
          onload: resolve,
          onerror: (error) => reject(error || new Error("GM_download failed")),
          ontimeout: () => reject(new Error("GM_download timed out"))
        });
      });
    }
    async function exportMainImage() {
      const result = await readPreviewImage(
        { profile: "userscript-v1", mode: "read" },
        {
          documentObject,
          fetchImpl,
          FileReaderCtor: documentObject.defaultView?.FileReader
        }
      );
      if (result.kind === "empty") return null;
      const filename = `${getDocumentTitle()}.${extensionFromMime(result.mime)}`;
      const url = result.payload.data;
      if (typeof gmDownload === "function") {
        await gmDownloadPromise(url, filename);
      } else {
        fallbackDownload(url, filename);
      }
      return { filename };
    }
    return {
      exportMainImage,
      getVisibleImages,
      getDocumentTitle
    };
  }

  // src/userscripts/feishu-preview-image-export/feishu-preview-image-export.entry.js
  (function() {
    "use strict";
    const SCRIPT_NAME = "Feishu Preview Image Export";
    const ROOT_ID = "feishu-pie-root";
    const STYLE_ID = `${ROOT_ID}-style`;
    let toaster = null;
    function ensureToaster() {
      if (toaster) return toaster;
      let root = document.getElementById(ROOT_ID);
      if (!root) {
        root = document.createElement("div");
        root.id = ROOT_ID;
        document.documentElement.append(root);
      }
      applyTheme(root);
      toaster = createToaster({ root });
      if (!document.getElementById(STYLE_ID)) {
        const style = document.createElement("style");
        style.id = STYLE_ID;
        style.textContent = [
          buildTokenCss({
            rootSelector: `#${ROOT_ID}`,
            accent: "oklch(55% 0.15 250)",
            accentDark: "oklch(70% 0.13 250)"
          }),
          // 让 toast 叠在预览页之上，root 自身不拦截页面交互
          `#${ROOT_ID} { position: fixed; inset: 0; z-index: 2147483647; pointer-events: none; }`,
          toaster.cssText
        ].join("\n\n");
        document.head.append(style);
      }
      return toaster;
    }
    const runtime = createImageExportRuntime({
      documentObject: document,
      fetchImpl: typeof fetch === "function" ? fetch.bind(globalThis) : null,
      gmDownload: typeof GM_download === "function" ? GM_download : null
    });
    function runExport() {
      const activeToaster = ensureToaster();
      if (!runtime.getVisibleImages().length) {
        activeToaster.show({ message: "当前页面没有找到可导出的主图。", tone: "info" });
        return;
      }
      const progress = activeToaster.showProgress({ message: "正在导出主图…" });
      runtime.exportMainImage().then((result) => {
        if (result) {
          progress.done(`已导出 ${result.filename}`);
        } else {
          progress.done("当前页面没有找到可导出的主图。");
        }
      }).catch((error) => {
        console.error(`${SCRIPT_NAME}: export failed.`, error);
        progress.fail(toUserMessage(error));
      });
    }
    if (typeof GM_registerMenuCommand === "function") {
      GM_registerMenuCommand("导出当前飞书主图", runExport);
    }
  })();
})();
// @license      MIT
