// ==UserScript==
// @name         Codex Quota Compass
// @name:zh-CN   Codex 配额统计
// @name:en      Codex Quota Compass
// @namespace    https://github.com/dzshzx/custom-user-js-scripts
// @version      0.4.1
// @description  Show Codex quota windows, daily usage, client summaries, and weekly estimates on chatgpt.com.
// @description:zh-CN  在 chatgpt.com 展示 Codex 配额窗口、每日用量、客户端汇总和周额度估算。
// @description:en     Show Codex quota windows, daily usage, client summaries, and weekly estimates on chatgpt.com.
// @author       BlueSkyXN, dzshzx
// @match        https://chatgpt.com/*
// @connect      api.github.com
// @connect      gist.githubusercontent.com
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_xmlhttpRequest
// @grant        GM_addValueChangeListener
// @grant        GM_removeValueChangeListener
// @grant        GM_registerMenuCommand
// @run-at       document-idle
// @homepageURL  https://github.com/dzshzx/custom-user-js-scripts
// @supportURL   https://github.com/dzshzx/custom-user-js-scripts/issues
// @downloadURL  https://raw.githubusercontent.com/dzshzx/custom-user-js-scripts/master/dist/codex-quota-compass.user.js
// @updateURL    https://raw.githubusercontent.com/dzshzx/custom-user-js-scripts/master/dist/codex-quota-compass.user.js
// @license      MIT
// ==/UserScript==
// GENERATED by scripts/build-userscripts.mjs — do not edit by hand.
// Sources: src/userscripts/codex-quota-compass/ (rebuild with `npm run build`).
// Bridge stub: keeps the legacy install path alive for update discovery only.
(function () {
  'use strict';
  console.info('Codex Quota Compass: this legacy path is a bridge stub — install the real script from https://raw.githubusercontent.com/dzshzx/custom-user-js-scripts/master/dist/codex-quota-compass.user.js');
})();
